--liquibase formatted sql
--changeset i.german:v1_init

create table sensor_statistics
(
    id           bigint generated by default as identity primary key,
    total_count  int  not null,
    created_date date not null
);

create table sensor_type_statistics
(
    id      bigint generated by default as identity primary key,
    type    varchar(255) not null,
    count   bigint       not null,
    type_id int,
    foreign key (type_id) references sensor_statistics (id) on delete cascade
);
