--liquibase formatted sql
--changeset i.german:v1_init

create table if not exists sensor_type
(
    id   bigint generated by default as identity primary key,
    type varchar(50) not null unique
);

create table if not exists sensor_unit
(
    id   bigint generated by default as identity primary key,
    unit varchar(50) not null unique
);

create table sensor
(
    id          serial primary key,
    name        varchar(30) not null check (length(name) >= 3),
    model       varchar(15) not null,
    range_from  int         not null check (range_from > 0),
    range_to    int         not null check (range_to > range_from),
    type_id     int         not null,
    unit_id     int,
    location    varchar(40),
    description varchar(200),
    foreign key (type_id) references sensor_type (id) on delete cascade,
    foreign key (unit_id) references sensor_unit (id) on delete set null
);

create table users
(
    id       bigint generated by default as identity primary key,
    name     varchar(255) unique not null,
    password varchar(255)        not null,
    role     varchar(255)        not null
);


